/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated.submissions'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated.proposals'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated.privacy'
import { Route as AuthenticatedOrgRouteImport } from './routes/_authenticated.org'
import { Route as AuthenticatedOpsRouteImport } from './routes/_authenticated.ops'
import { Route as AuthenticatedGrantsRouteImport } from './routes/_authenticated.grants'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedProposalsIdRouteImport } from './routes/_authenticated.proposals.$id'
import { Route as AuthenticatedGrantsIdRouteImport } from './routes/_authenticated.grants.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminModulesRouteImport } from './routes/_authenticated.admin.modules'
import { Route as AuthenticatedAdminHistoryRouteImport } from './routes/_authenticated.admin.history'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated.admin.agents'
import { Route as ApiPublicHooksRssPollRouteImport } from './routes/api/public/hooks/rss-poll'
import { Route as ApiPublicHooksEnrichRouteImport } from './routes/api/public/hooks/enrich'
import { Route as ApiPublicHooksDiscoverRouteImport } from './routes/api/public/hooks/discover'
import { Route as ApiPublicHooksDeadlinesRouteImport } from './routes/api/public/hooks/deadlines'

const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgRoute = AuthenticatedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpsRoute = AuthenticatedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrantsRoute = AuthenticatedGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedProposalsIdRoute =
  AuthenticatedProposalsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProposalsRoute,
  } as any)
const AuthenticatedGrantsIdRoute = AuthenticatedGrantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedGrantsRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminModulesRoute =
  AuthenticatedAdminModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHistoryRoute =
  AuthenticatedAdminHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksRssPollRoute = ApiPublicHooksRssPollRouteImport.update({
  id: '/api/public/hooks/rss-poll',
  path: '/api/public/hooks/rss-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEnrichRoute = ApiPublicHooksEnrichRouteImport.update({
  id: '/api/public/hooks/enrich',
  path: '/api/public/hooks/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDiscoverRoute = ApiPublicHooksDiscoverRouteImport.update({
  id: '/api/public/hooks/discover',
  path: '/api/public/hooks/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDeadlinesRoute = ApiPublicHooksDeadlinesRouteImport.update({
  id: '/api/public/hooks/deadlines',
  path: '/api/public/hooks/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grants': typeof AuthenticatedGrantsRouteWithChildren
  '/ops': typeof AuthenticatedOpsRoute
  '/org': typeof AuthenticatedOrgRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/proposals': typeof AuthenticatedProposalsRouteWithChildren
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/history': typeof AuthenticatedAdminHistoryRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/grants/$id': typeof AuthenticatedGrantsIdRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/deadlines': typeof ApiPublicHooksDeadlinesRoute
  '/api/public/hooks/discover': typeof ApiPublicHooksDiscoverRoute
  '/api/public/hooks/enrich': typeof ApiPublicHooksEnrichRoute
  '/api/public/hooks/rss-poll': typeof ApiPublicHooksRssPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grants': typeof AuthenticatedGrantsRouteWithChildren
  '/ops': typeof AuthenticatedOpsRoute
  '/org': typeof AuthenticatedOrgRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/proposals': typeof AuthenticatedProposalsRouteWithChildren
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/history': typeof AuthenticatedAdminHistoryRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/grants/$id': typeof AuthenticatedGrantsIdRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/deadlines': typeof ApiPublicHooksDeadlinesRoute
  '/api/public/hooks/discover': typeof ApiPublicHooksDiscoverRoute
  '/api/public/hooks/enrich': typeof ApiPublicHooksEnrichRoute
  '/api/public/hooks/rss-poll': typeof ApiPublicHooksRssPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grants': typeof AuthenticatedGrantsRouteWithChildren
  '/_authenticated/ops': typeof AuthenticatedOpsRoute
  '/_authenticated/org': typeof AuthenticatedOrgRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/proposals': typeof AuthenticatedProposalsRouteWithChildren
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/history': typeof AuthenticatedAdminHistoryRoute
  '/_authenticated/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/grants/$id': typeof AuthenticatedGrantsIdRoute
  '/_authenticated/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/deadlines': typeof ApiPublicHooksDeadlinesRoute
  '/api/public/hooks/discover': typeof ApiPublicHooksDiscoverRoute
  '/api/public/hooks/enrich': typeof ApiPublicHooksEnrichRoute
  '/api/public/hooks/rss-poll': typeof ApiPublicHooksRssPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compliance'
    | '/admin'
    | '/dashboard'
    | '/grants'
    | '/ops'
    | '/org'
    | '/privacy'
    | '/proposals'
    | '/submissions'
    | '/admin/agents'
    | '/admin/history'
    | '/admin/modules'
    | '/admin/users'
    | '/grants/$id'
    | '/proposals/$id'
    | '/admin/'
    | '/api/public/hooks/deadlines'
    | '/api/public/hooks/discover'
    | '/api/public/hooks/enrich'
    | '/api/public/hooks/rss-poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compliance'
    | '/dashboard'
    | '/grants'
    | '/ops'
    | '/org'
    | '/privacy'
    | '/proposals'
    | '/submissions'
    | '/admin/agents'
    | '/admin/history'
    | '/admin/modules'
    | '/admin/users'
    | '/grants/$id'
    | '/proposals/$id'
    | '/admin'
    | '/api/public/hooks/deadlines'
    | '/api/public/hooks/discover'
    | '/api/public/hooks/enrich'
    | '/api/public/hooks/rss-poll'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compliance'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/grants'
    | '/_authenticated/ops'
    | '/_authenticated/org'
    | '/_authenticated/privacy'
    | '/_authenticated/proposals'
    | '/_authenticated/submissions'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/history'
    | '/_authenticated/admin/modules'
    | '/_authenticated/admin/users'
    | '/_authenticated/grants/$id'
    | '/_authenticated/proposals/$id'
    | '/_authenticated/admin/'
    | '/api/public/hooks/deadlines'
    | '/api/public/hooks/discover'
    | '/api/public/hooks/enrich'
    | '/api/public/hooks/rss-poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComplianceRoute: typeof ComplianceRoute
  ApiPublicHooksDeadlinesRoute: typeof ApiPublicHooksDeadlinesRoute
  ApiPublicHooksDiscoverRoute: typeof ApiPublicHooksDiscoverRoute
  ApiPublicHooksEnrichRoute: typeof ApiPublicHooksEnrichRoute
  ApiPublicHooksRssPollRoute: typeof ApiPublicHooksRssPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org': {
      id: '/_authenticated/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthenticatedOrgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops': {
      id: '/_authenticated/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AuthenticatedOpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grants': {
      id: '/_authenticated/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof AuthenticatedGrantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/proposals/$id': {
      id: '/_authenticated/proposals/$id'
      path: '/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthenticatedProposalsIdRouteImport
      parentRoute: typeof AuthenticatedProposalsRoute
    }
    '/_authenticated/grants/$id': {
      id: '/_authenticated/grants/$id'
      path: '/$id'
      fullPath: '/grants/$id'
      preLoaderRoute: typeof AuthenticatedGrantsIdRouteImport
      parentRoute: typeof AuthenticatedGrantsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modules': {
      id: '/_authenticated/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/history': {
      id: '/_authenticated/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AuthenticatedAdminHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/rss-poll': {
      id: '/api/public/hooks/rss-poll'
      path: '/api/public/hooks/rss-poll'
      fullPath: '/api/public/hooks/rss-poll'
      preLoaderRoute: typeof ApiPublicHooksRssPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enrich': {
      id: '/api/public/hooks/enrich'
      path: '/api/public/hooks/enrich'
      fullPath: '/api/public/hooks/enrich'
      preLoaderRoute: typeof ApiPublicHooksEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover': {
      id: '/api/public/hooks/discover'
      path: '/api/public/hooks/discover'
      fullPath: '/api/public/hooks/discover'
      preLoaderRoute: typeof ApiPublicHooksDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deadlines': {
      id: '/api/public/hooks/deadlines'
      path: '/api/public/hooks/deadlines'
      fullPath: '/api/public/hooks/deadlines'
      preLoaderRoute: typeof ApiPublicHooksDeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminHistoryRoute: typeof AuthenticatedAdminHistoryRoute
  AuthenticatedAdminModulesRoute: typeof AuthenticatedAdminModulesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminHistoryRoute: AuthenticatedAdminHistoryRoute,
  AuthenticatedAdminModulesRoute: AuthenticatedAdminModulesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedGrantsRouteChildren {
  AuthenticatedGrantsIdRoute: typeof AuthenticatedGrantsIdRoute
}

const AuthenticatedGrantsRouteChildren: AuthenticatedGrantsRouteChildren = {
  AuthenticatedGrantsIdRoute: AuthenticatedGrantsIdRoute,
}

const AuthenticatedGrantsRouteWithChildren =
  AuthenticatedGrantsRoute._addFileChildren(AuthenticatedGrantsRouteChildren)

interface AuthenticatedProposalsRouteChildren {
  AuthenticatedProposalsIdRoute: typeof AuthenticatedProposalsIdRoute
}

const AuthenticatedProposalsRouteChildren: AuthenticatedProposalsRouteChildren =
  {
    AuthenticatedProposalsIdRoute: AuthenticatedProposalsIdRoute,
  }

const AuthenticatedProposalsRouteWithChildren =
  AuthenticatedProposalsRoute._addFileChildren(
    AuthenticatedProposalsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGrantsRoute: typeof AuthenticatedGrantsRouteWithChildren
  AuthenticatedOpsRoute: typeof AuthenticatedOpsRoute
  AuthenticatedOrgRoute: typeof AuthenticatedOrgRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRouteWithChildren
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGrantsRoute: AuthenticatedGrantsRouteWithChildren,
  AuthenticatedOpsRoute: AuthenticatedOpsRoute,
  AuthenticatedOrgRoute: AuthenticatedOrgRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRouteWithChildren,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ComplianceRoute: ComplianceRoute,
  ApiPublicHooksDeadlinesRoute: ApiPublicHooksDeadlinesRoute,
  ApiPublicHooksDiscoverRoute: ApiPublicHooksDiscoverRoute,
  ApiPublicHooksEnrichRoute: ApiPublicHooksEnrichRoute,
  ApiPublicHooksRssPollRoute: ApiPublicHooksRssPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
