/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrgRouteImport } from './routes/_authenticated.org'
import { Route as AuthenticatedGrantsRouteImport } from './routes/_authenticated.grants'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as ApiPublicHooksEnrichRouteImport } from './routes/api/public/hooks/enrich'
import { Route as ApiPublicHooksDiscoverRouteImport } from './routes/api/public/hooks/discover'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgRoute = AuthenticatedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrantsRoute = AuthenticatedGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksEnrichRoute = ApiPublicHooksEnrichRouteImport.update({
  id: '/api/public/hooks/enrich',
  path: '/api/public/hooks/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDiscoverRoute = ApiPublicHooksDiscoverRouteImport.update({
  id: '/api/public/hooks/discover',
  path: '/api/public/hooks/discover',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grants': typeof AuthenticatedGrantsRoute
  '/org': typeof AuthenticatedOrgRoute
  '/api/public/hooks/discover': typeof ApiPublicHooksDiscoverRoute
  '/api/public/hooks/enrich': typeof ApiPublicHooksEnrichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grants': typeof AuthenticatedGrantsRoute
  '/org': typeof AuthenticatedOrgRoute
  '/api/public/hooks/discover': typeof ApiPublicHooksDiscoverRoute
  '/api/public/hooks/enrich': typeof ApiPublicHooksEnrichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grants': typeof AuthenticatedGrantsRoute
  '/_authenticated/org': typeof AuthenticatedOrgRoute
  '/api/public/hooks/discover': typeof ApiPublicHooksDiscoverRoute
  '/api/public/hooks/enrich': typeof ApiPublicHooksEnrichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/grants'
    | '/org'
    | '/api/public/hooks/discover'
    | '/api/public/hooks/enrich'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/grants'
    | '/org'
    | '/api/public/hooks/discover'
    | '/api/public/hooks/enrich'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/grants'
    | '/_authenticated/org'
    | '/api/public/hooks/discover'
    | '/api/public/hooks/enrich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksDiscoverRoute: typeof ApiPublicHooksDiscoverRoute
  ApiPublicHooksEnrichRoute: typeof ApiPublicHooksEnrichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/org': {
      id: '/_authenticated/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthenticatedOrgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grants': {
      id: '/_authenticated/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof AuthenticatedGrantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/enrich': {
      id: '/api/public/hooks/enrich'
      path: '/api/public/hooks/enrich'
      fullPath: '/api/public/hooks/enrich'
      preLoaderRoute: typeof ApiPublicHooksEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover': {
      id: '/api/public/hooks/discover'
      path: '/api/public/hooks/discover'
      fullPath: '/api/public/hooks/discover'
      preLoaderRoute: typeof ApiPublicHooksDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGrantsRoute: typeof AuthenticatedGrantsRoute
  AuthenticatedOrgRoute: typeof AuthenticatedOrgRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGrantsRoute: AuthenticatedGrantsRoute,
  AuthenticatedOrgRoute: AuthenticatedOrgRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksDiscoverRoute: ApiPublicHooksDiscoverRoute,
  ApiPublicHooksEnrichRoute: ApiPublicHooksEnrichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
